name: new_project
description: A new Flutter project.
publish_to: 'none' # This line prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.4+5  # Add the camera package version with caret for version flexibility
  image_picker: ^0.8.4+4  # Add the latest version of image_picker
  cupertino_icons: ^1.0.2  # Add Cupertino Icons package version with caret for version flexibility

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Add Flutter Lints package version with caret for version flexibility

flutter:
  uses-material-design: true
